import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";
import { useState, useEffect } from "react";
import { Chart, registerables } from "chart.js";
import { Line } from "react-chartjs-2";

const Home: NextPage = () => {
  //都道府県一覧のチェックボックス
  const [data, setData] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch("/api/prefectures");
      const resArray = await response.json();
      const aaa = [
        { prefCode: 1, prefName: "青森" },
        { prefCode: 2, prefName: "岩手" },
      ];
      setData(resArray.data.result);
    };
    fetchData();
  }, []);

  //人口構成グラフ

  const labels: Array<Number> = [
    1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035,
    2040, 2045,
  ];

  const graphData = {
    labels: labels,
    datasets: [
      {
        label: "青森",
        data: [
          12707, 12571, 12602, 12199, 11518, 10888, 10133, 9275, 8431, 7610,
          6816, 6048, 5324,
        ],
        borderColor: "rgb(75, 192, 192)",
      },
    ],
  };

  const options: object = {
    maintainAspectRatio: false,
    responsive: false,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Population composition</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <h1 className={styles.title}>都道府県別人口構成</h1>
      </header>
      <p className={styles.description}>都道府県一覧</p>
      <main className={styles.main}>
        <div className={styles.grid}>
          {data.map((pre) => (
            <div key={pre.prefCode}>
              <input type="checkbox" />
              <label>{pre.prefName}</label>
            </div>
          ))}
        </div>
        <Line height={300} width={400} data={graphData} options={options} />
      </main>

      <footer className={styles.footer}>Crested by kazushi</footer>
    </div>
  );
};

/* export const getSeverSideProps: GetServerSideProps = async () => {
  const response = await fetch("/page/api/prefectures");
  const data = response.json()
  console.log(typeof data);

   const aaa: Array<Atype> = [
    { prefCode: 1, prefName: "青森" },
    { prefCode: 2, prefName: "dv" },
  ]; 

  return { props: { data } };
}; */
export default Home;
